CREATE TABLE IF NOT EXISTS chatbot_logs (
  id SERIAL PRIMARY KEY,
  scenario TEXT NOT NULL,
  location TEXT,
  provider TEXT,
  image_uploaded BOOLEAN DEFAULT FALSE,
  image_caption TEXT,
  original_input TEXT,
  detected_language TEXT,
  translated_model_input TEXT,
  final_model_input TEXT,
  final_model_input_v1_2 TEXT,
  model_version TEXT,
  predicted_hazard_category TEXT,
  predicted_risk_level TEXT,
  sub_hazard TEXT,
  manual_review_flag BOOLEAN,
  needs_more_information BOOLEAN,
  clarification_question TEXT,
  hazard_confidence DOUBLE PRECISION,
  hazard_confidence_percent TEXT,
  risk_method TEXT,
  image_caption_status TEXT,
  risk_confidence DOUBLE PRECISION,
  risk_confidence_percent TEXT,
  overall_confidence DOUBLE PRECISION,
  overall_confidence_percent TEXT,
  overall_confidence_label TEXT,
  hazard_probabilities TEXT,
  risk_probabilities TEXT,
  confidence_note TEXT,
  urgency TEXT,
  decision_support_recommendation TEXT,
  recommendation TEXT,
  corrective_action_plan JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);